### ISSUE TITLE
Vertical Metrics

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#15]
As we agreed in the last meeting, I revised the vertical metrics after the resizing (`lang-build` branch at commit `bf1024c`). I've tested the following new values for the variable vertical metrics.

Please apply them before the next build of the fonts for each country so we can check how they will work for each model, and see if that solves the current Fail reported regarding vertical metrics for all of them.

````
Metrics         |  Short  |  Long   |
                | Masters | Masters |
----------------|---------|---------|
sTypoAscender   |   1275  |   2040  |
sTypoDescender  |   -375  |  -1020  |
sTypoLinegap    |      0  |      0  |
hhea Ascender   |   1275  |   2040  |
hhea Descender  |   -375  |  -1020  |
hhea Linegap    |      0  |      0  |
winAscent       |   1313  |   2040  |
winDescent      |    400  |   1020  |
````

#### Comparative images
`old` = Vertical metrics saw at the meeting || `new` = proposed values
(you can click on the image to enlarge it)

![VM4-VM6-v0209](https://github.com/TypeTogether/Playpen/assets/48698976/48ebb28e-2486-4504-8220-6e2c37160977)

**Comment by josescaglione** [comment]
@vv-monsalve I am sorry to be bearing bad news. We encountered an issue when laying out the FR_Trad specimen. I fear there is a cropping in INDD. Please see the attached.

This only seems to be visible in the regular weight for the time being. It shows in INDD and it exports cropped as well.

<img width="583" alt="Screenshot 2024-01-09 at 06 41 33" src="https://github.com/TypeTogether/Playwrite/assets/1699496/cd1cda08-7d2d-4d48-81c1-336baa2dff5a">

**Comment by vv-monsalve** [comment]
Thanks, @josescaglione, for the report. This is significant news since this would modify the value of the long masters, and that will impact all the fonts. I'll perform some tests on my end and come back here afterward with added thoughts.

**Comment by josescaglione** [comment]
hi @vv-monsalve after a few additional tests we were unable to replicate the error and the fonts are working correctly. I apologize for not closing the issue again.

**Comment by josescaglione** [comment]
Closing it now

**Comment by vv-monsalve** [comment]
@josescaglione I've tested the font again on InDesign and I'm not seeing any clipping indeed.
