### ISSUE TITLE
Slant value should be negative

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#18]
According to the spec:
> Note that the scale for the Slant axis is interpreted as the angle of slant in counter-clockwise degrees from upright. This means that a typical, right-leaning oblique design will have a negative slant value.

There is a Fail reported related to this for the VF at commit `ea9393d`

<details><summary>🔥 <b>FAIL:</b> Checking direction of slnt axis angles (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/slant_direction">com.google.fonts/check/slant_direction</a>)</summary><div>

>
>The 'slnt' axis values are defined as negative values for a clockwise (right) lean, and positive values for counter-clockwise lean. This is counter-intuitive for many designers who are used to think of a positive slant as a lean to the right.
>
>This check ensures that the slant axis direction is consistent with the specs.
>
>https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_slnt
>
* 🔥 **FAIL** The right-leaning glyphs have a positive 'slnt' axis value, which is likely a mistake. It needs to be negative to lean rightwards. [code: positive-value-for-clockwise-lean]
</div></details>

**Comment by vv-monsalve** [comment]
This value is still positive in the source file in `lang-build` branch at commit `658f99f`.

@simoncozens Is this what is preventing `builder2` from creating the Italic fonts?

**Comment by simoncozens** [comment]
The italic fonts are being built correctly, but I agree that the slant axis should be changed in the sources.

The [specification of the slnt axis](https://learn.microsoft.com/en-gb/typography/opentype/spec/dvaraxistag_slnt) says that

> Values can be interpreted as the angle, in counter-clockwise degrees

Glyphs is a bit funny here - it interprets italic angles in *static* fonts (e.g. post.italicAngle) as clockwise claiming this is ["more intuitive"](https://forum.glyphsapp.com/t/italic-angles/589/6), and then flips the sign on export. But it isn't what the spec says, and it means when people use the same values for their `slnt` axes they produce fonts that are not compliant with the spec.

**Comment by vv-monsalve** [comment]
Confirmed this is ok on the source file a commit `cc1f569`. Closing it now :)
