### ISSUE TITLE
Country recipes data

### ISSUE THREAD

**Issue by davelab6** [TypeTogether/Playwrite#2]
In the [Font Families List google sheet](https://docs.google.com/spreadsheets/d/1nA9Z8vDahOpjzaftFVOLyOxrsDPPCaorA4AnAJnhtpE) we are establishing the child families to derive from the VF. 

Please add cols for each axis and OT feature, and then in each row, specify the values for them, in order for the GF API to do the derivation using fonttools (similar to [github.com/twardoch/fonttools-opentype-feature-freezer](https://github.com/twardoch/fonttools-opentype-feature-freezer)) based on these data being in the GF METADATA file. (If you aren't familiar with this file, see [gf-guide/metadata](https://googlefonts.github.io/gf-guide/metadata.html) and eg [literata/METADATA.pb](https://github.com/google/fonts/blob/main/ofl/literata/METADATA.pb))

**Comment by vv-monsalve** [comment]
@davelab6 @simoncozens 

This information is included in the [models-all.csv](https://github.com/TypeTogether/Playwrite/blob/lang-build/sources/data/models-all.csv) file.

Let's close this here. Please feel free to reopen in case you consider something else is missing.
