### ISSUE TITLE
Guidelines variant

### ISSUE THREAD

**Issue by josescaglione** [TypeTogether/Playwrite#23]
We have the files ready for producing fonts with guidelines, but we feel we should only use one of the weights to make things simpler. What do you think?

<img width="368" alt="Screenshot 2023-10-26 at 15 01 52" src="https://github.com/TypeTogether/Playwrite/assets/1699496/84712f99-67fa-430e-b3eb-bfd1f241fa0f">

**Comment by chrissimpkins** [comment]
Does anyone have examples of actual handwriting textbooks used with kids in elementary school?  I think that it would be helpful to understand how education documentation is currently printed to talk through the combinations required here.

**Comment by chrissimpkins** [comment]
IMO the following seem mandatory:

- Default Playwrite (no guidelines)
- Dotted Playwrite **with guidelines**
- Solid Playwrite **with guidelines**

Beyond that, I'm not sure.  I think that we need feedback on handwriting education worksheet layout if we don't have that.

**Comment by vv-monsalve** [comment]
In October 2023, a user wrote:

> It would be absolutely amazing if primary teachers could have a font in Google Docs that allows the person making the doc to add primary lines and the possibility of letter tracing. As a teacher there is so little time to create and since Google has such an awesome program it would be so helpful if we could create resources for our students using Google Docs with a font like that. I have seen something similar called KG Primary Penmanship and would love to be able to have something like that available to create resources for my students.

In July this year, another user wrote with a similar request, also mentioning the KG Primary fonts.

> We just had a teacher asking for this today and unfortunately our only option was to have them use Microsoft Word as they have a font called Microsoft ABC Dashed which my teachers use.  There are also TTFs available, such as KG Lined and KG Lined - No Spaces, but those can't be used in Google Apps.

I couldn't find `Microsoft ABC Dashed` on the web. Now the `KG Primary` fonts are available at the [teachers pay teachers](https://www.teacherspayteachers.com/) site (among others).

#### KG Primary Dots Lined

dotted letters with guidelines also for the `space` character
<img width="518" alt="Screenshot 2024-08-07 at 13 46 36" src="https://github.com/user-attachments/assets/d903ba5b-ca0e-4979-9e4e-7bea0551996f">

#### KG Primary Lined NOSPACE
solid letters with guidelines, but not for the `space` character. In this font, the `|` character is left empty to provide the lines only

<img width="518" alt="Screenshot 2024-08-07 at 13 46 42" src="https://github.com/user-attachments/assets/5a994302-2449-4a04-adf2-eac114200bd3">

The latter was created to sort out a couple of identified issues for teachers working on PowerPoint, as the author specifies in the [Description of their fonts](https://www.teacherspayteachers.com/Product/KG-Primary-Dots-Lined-Personal-Use-559628?st=dd1bce6dfa4ff90bc40a462c75aab16e).

So, based on these requests and fonts as a reference, I believe we should include at least a similar option of an "empty" character for the teachers to create _empty_ guidelines within both fonts, the solid and dotted with guidelines.

**Comment by vv-monsalve** [comment]
> Following our latest discussions, we've agreed to use only the Regular weight to produce the Guides style.

We agreed to use the 'ExtraLight' thickness along with the guidelines, but as the "Regular" style for this variant.

**Comment by davelab6** [comment]
>  I believe we should include at least a similar option of an "empty" character for the teachers to create empty guidelines within both fonts, the solid and dotted with guidelines.

Perhaps space has no ink and underscore `_` has the ink>

**Comment by vv-monsalve** [comment]
> Perhaps space has no ink and underscore `_` has the ink?

So it would be:

- **Default Playwrite (no guidelines)**
    - Family Name: e.g. `Playwrite DK Uloopet`
- **Solid Playwrite with guidelines**
    - Displaying letters in the thinnest weight in the designspace: Thin.
    - Space without ink and underscore `_` with the guidelines only. 
       It could be the same width as the space, so it can be used as an inked replacement for it.
    - Family name: `Playwrite DK Uloopet Guides`
- **Dotted Playwrite with guidelines**
   - Displaying dots in a weight yet to be decided.
   - Space without ink; `_` inked
   - Family name: `Playwrite DK Uloopet Dots Guides`

**Comment by davelab6** [comment]
@josescaglione to your original question, kindly, I don't get it. Aren't the guidelines being made by script? and aren't all weight styles belonging to one family? So why only use one of the weights - how does that make things simpler? :)

**Comment by josescaglione** [comment]
Sorry @davelab6 my comment was in the context of a long discussion regarding the length of font names. I though that if we use a single weight then we can simply say "dotted" as the style name, whereas multiple weights would require a more involved solution.

**Comment by vv-monsalve** [comment]
> > Following our latest discussions, we've agreed to use only the Regular weight to produce the Guides style.
> 
> We agreed to use the 'ExtraLight' thickness along with the guidelines, but as the "Regular" style for this variant.

Due to the character limit, we've decided to create the Guides and Dots versions only for the "Regular" style. 

However, we've also agreed not to use the actual Regular weight but a lighter one to serve better the purpose of tracing during teaching. 

The lighter letters in the design space correspond to the Thin weight, so that's why I'm suggesting we use those shapes.

**Comment by chrissimpkins** [comment]
We were able to dig up some of our kids' old handwriting journals and workbooks from elementary school.  I thought that this might be useful to inform the approach to the Playwrite guidelines variants.  It looks like the approach used in these Zaner-Bloser model education tools is guidelines for:

- cap height (solid line)
- x-height (dashed line)
- baseline (solid line)

![IMG_0136](https://github.com/user-attachments/assets/ea40ad46-8cd8-480f-8323-852f84915d25)

![IMG_0137](https://github.com/user-attachments/assets/c675b550-9d04-46c4-b22a-824fb7886abd)

![IMG_0138](https://github.com/user-attachments/assets/bb2f2a55-5339-4838-bac0-d25de1cafd3f)

![IMG_0139](https://github.com/user-attachments/assets/73a528b1-2168-47f8-8375-dbf2af472ab7)

![IMG_0140](https://github.com/user-attachments/assets/a6864425-739a-45b0-aef7-e607499bff97)

![IMG_0141](https://github.com/user-attachments/assets/50ba67c8-3596-462f-97d1-eb35c187f815)

**Comment by simoncozens** [comment]
Additional thought: If we are going to use "space" for space without guidelines and "underscore" for space with guidelines, they'd better both have the same advance width.

**Comment by vv-monsalve** [comment]
At today's meeting, reviewing the decisions for the Guides variants, we agreed on:

**Solid Playwrite with guidelines**
  - The selected weight to be used in these fonts is ExtraLight (image below).
  - Space without ink   - Underscore `_` with the guidelines only. 
     - We confirmed it should have the same width as the space so that it can be used as an inked replacement for it.   - Guides style
     - Solid. No dashes
     - The baseline should be thicker (as it currently is, image below)
  - Family name example: `Playwrite DK Uloopet Guides`
    
**Next items to solve**

- [ ] Fixing the guidelines gaps 

    @simoncozens, José suggested that for the "non-spacing" glyphs such some connections, the guides could use the outline width instead of the glyph's advanced width

<img width="932" alt="Screenshot 2024-10-16 at 11 53 17" src="https://github.com/user-attachments/assets/02bdaf54-0bc4-433e-b6d8-280edd12edb6">

- [ ] Underscore

   Two variants for the `underscore` are needed: 
    - With outlines for the standard (no-guides) family
    - Non-outlines for the Guides variant. This should be turned into the main one when creating the Guides version.

**Comment by simoncozens** [comment]
We don't need variants for the underscore. The way I have implemented the code to make the guidelines variant, you can turn on and off outlines and guidelines on a per-glyph basis. So we can turn off outlines for the underscore glyph and turn off guidelines for the space glyph. This is controlled using Glyphs userData on the glyph object. The problem with the gaps is also fixed.

**Comment by josescaglione** [comment]
@vv-monsalve please check the Fixes branch and merge into main as discussed. I will make the change immediately after that


> > So we can turn off outlines for the underscore glyph and turn off guidelines for the space glyph. This is controlled using Glyphs userData on the glyph object.
> 
> Awesome! This is even better :). @josescaglione So the only remaining thing now would be to make the underscore to have the Advanced width of the `space`.

**Comment by vv-monsalve** [comment]
Goal completed.
