### ISSUE TITLE
ele geminada not fully working

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#24]
The `ele geminada` required for the Catalán is not fully working on some models. The following cases were found in fonts at commit `5d75173`

E.g. Argentina

<img width="183" alt="Screen Shot 2023-11-14 at 21 14 46" src="https://github.com/TypeTogether/Playwrite/assets/48698976/21d7b323-4816-447e-b083-5b0d38a15e71">

<img width="2114" alt="Playwrite-ele-geminada" src="https://github.com/TypeTogether/Playwrite/assets/48698976/d8841e17-e6a8-488f-aa29-0fa7a63254ed">

----

This is also happening in:
- Australia NSW
- Australia QLD
- Australia SA
- Australia TAS
- Australia VIC
    <img width="1725" alt="Screen Shot 2023-11-14 at 23 36 50" src="https://github.com/TypeTogether/Playwrite/assets/48698976/393f4cb6-c509-44a8-81dd-3a7a86c17926">

**Comment by casasin** [comment]
@vv-monsalve : This has been fixed but not in all fonts as we're testing the sandbox only by now. I can update all if you want.

**Comment by vv-monsalve** [comment]
For the time being it's ok only in the testing fonts. Let's keep the issue open until we start working on the incorporation of all the models.

**Comment by vv-monsalve** [comment]
This is working ok for our three test fonts `CO` `FR Trad` `GB S` in the `lang-build `branch at commit 658f99f.

So, closing this here. I'll reopen it if any other case is found

<img width="2288" alt="Screen Shot 2024-02-06 at 16 31 48" src="https://github.com/TypeTogether/Playwrite/assets/48698976/6650f0c9-31ba-40ed-913b-ead2cbdca974">
