### ISSUE TITLE
Diacritic marks issues

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#26]
I'll report here all the marks issues spotted. The following cases were found in fonts at commit `5d75173`

### Ydotbelow

In `Ydotbelow` the dot is typically placed to the right of the letter.

**Australia NSW**

<img width="1751" alt="Screen Shot 2023-11-14 at 23 12 08" src="https://github.com/TypeTogether/Playwrite/assets/48698976/0b9e872f-f4d0-442a-9a71-35eb72c060bc">

**Comment by vv-monsalve** [comment]
The fonts in the `lang-build` branch at commit `658f99f` still need to place the dot on the right side of the letter.

England Semijoin 
<img width="1139" alt="Screen Shot 2024-02-06 at 16 26 50" src="https://github.com/TypeTogether/Playwrite/assets/48698976/cf3fd166-0390-49a2-a7cf-e67cdec51c75">

**Comment by josescaglione** [comment]
Hi @vv-monsalve we consulted with Donny Truong and sent him the samples we were using
<img width="278" alt="Screenshot 2024-02-07 at 08 50 37" src="https://github.com/TypeTogether/Playwrite/assets/1699496/f89f4bc2-3216-4804-8d37-899e56fc7c79">
<img width="259" alt="Screenshot 2024-02-07 at 08 52 07" src="https://github.com/TypeTogether/Playwrite/assets/1699496/a2509010-81eb-4150-9b74-16fdb8af0645">

and also sent him the sample in the unjoined version

<img width="273" alt="Screenshot 2024-02-07 at 08 57 53" src="https://github.com/TypeTogether/Playwrite/assets/1699496/eb3870be-9c15-460d-adce-dba9e16f448b">



His reply:
For the looped y’s, the underdot you have might be OK, but the unlooped is odd. My recommendation would be to customize the descenders with the dots under them. Make the dotted-y its own glyph. I created a rough illustration to demonstrate what I mean. Let me know if you have further questions.
<img width="208" alt="Screenshot 2024-02-07 at 14 28 13" src="https://github.com/TypeTogether/Playwrite/assets/1699496/2d910166-6016-42c2-950f-5e49dc585003">


And I add:
And we could try the same approach with the looped version but that is not what the current viet model looks like:

<img width="289" alt="Screenshot 2024-02-07 at 14 28 56" src="https://github.com/TypeTogether/Playwrite/assets/1699496/95976773-b8a8-4b1a-bb07-4f4b4cef72d6">

**Comment by josescaglione** [comment]
Another consultant got back to me. His notes below:

- - - - 
About this ydotbelow, I'm looking at many VN primary handwriting exercises/textbooks to find some references. But the thing is this character is not so frequent in our language. I've been looking through some but have only found one example through a picture of a teacher (https://www.facebook.com/lathi.thuthuy.9/) You can see here a tiny dot below the bowl in the word "huỵch".

<img width="152" alt="Screenshot 2024-02-08 at 11 38 46" src="https://github.com/TypeTogether/Playwrite/assets/1699496/61c0dfde-db66-42fa-bfbb-fca124c8c8c9">


I tried writing them to see how my hand goes with the muscle memory and it's more natural to have it below the bowl. 


<img width="677" alt="Screenshot 2024-02-08 at 11 40 09" src="https://github.com/TypeTogether/Playwrite/assets/1699496/178b7b3f-f6ea-4a64-aa73-9a470b904a05">

**Comment by josescaglione** [comment]
Now, the problem is that all accents are positioned on the fly to reduce font size and feature file processing load. So, if we need to have a precomposed shape for any of the versions of ydotbelow then we need to have one for all. Adding this implies working on 4 versions: precursive, .mod, .jmc, .cnt on all 16 masters, so 208 designs (many would be composites)

I wonder if we should place on the right side for precursive and .mod only, and leave on the right for the other two.
<img width="532" alt="Screenshot 2024-02-08 at 11 47 56" src="https://github.com/TypeTogether/Playwrite/assets/1699496/427d2539-4a75-4633-b117-b0fcb54d9681">


<img width="534" alt="Screenshot 2024-02-08 at 11 47 42" src="https://github.com/TypeTogether/Playwrite/assets/1699496/3e672186-1861-4918-b2d0-3a19b107ad44">

**Comment by vv-monsalve** [comment]
> all accents are positioned on the fly to reduce font size and feature file processing load. So, if we need to have a precomposed shape for any of the versions of ydotbelow then we need to have one for all.

> I wonder if we should place on the right side for precursive and .mod only, and leave on the right for the other two.

<img width="571" alt="Screen Shot 2024-02-08 at 10 09 59" src="https://github.com/TypeTogether/Playwrite/assets/48698976/71321512-92b0-4323-9e82-6f0ba866f600">

I will advocate for any solution that favors on-the-fly composition and doesn't imply a change in shape. Nhung has told us it could always be at the right since there are no combinations of letters that could create a clash (on standard fonts). Although I recognize a joined model could bring different situations, thus it could be this one you propose for precursive and mod.

**Comment by davelab6** [comment]
I concur with @vv-monsalve

**Comment by josescaglione** [comment]
ok, its decided then, thank you both for reviewing!

**Comment by vv-monsalve** [comment]
This was fixed for most of the fonts in `lang-build` branch at commit `cc1f569`. 

However, you would like to review the following cases to refine the dot position.

- **Playwrite CO** and **Playwrite MX**: bit right and up

    <img width="186" alt="Screen Shot 2024-03-01 at 19 10 28" src="https://github.com/TypeTogether/Playwrite/assets/48698976/67b42e5d-5bf3-46ae-8417-53e160eaed0f">

**Comment by vv-monsalve** [comment]
Ok in latest fonts at c08ea9f1da47a53d097fd551646b8d1c3fb0c8ee
