### ISSUE TITLE
Quotation marks position

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#28]
The quotation marks position is working with Uppercase and ascender height. However, when used with lowercase letters they look shifted up. Should we find a compromise in the position by making it a bit lower?

E.g. **France Traditional**

<img width="523" alt="Screen Shot 2023-11-29 at 23 07 11" src="https://github.com/TypeTogether/Playwrite/assets/48698976/704df68b-a4d6-48e6-a2cd-0153cdc7e2aa">

**Comment by vv-monsalve** [comment]
This is the position of the current quotes in the France Traditional (one of the highest ascenders)  in the `lang-build` branch at commit `658f99f `

They look good for the v1 release. @davelab6
<br>

<img width="723" alt="Screen Shot 2024-02-06 at 16 06 14" src="https://github.com/TypeTogether/Playwrite/assets/48698976/44840f64-0da2-46d9-b57b-73e929f6950f">


<img width="2288" alt="Screen Shot 2024-02-06 at 16 00 37" src="https://github.com/TypeTogether/Playwrite/assets/48698976/7fe38bd6-5e08-415a-8f30-d739b262ee19">

**Comment by casasin** [comment]
@vv-monsalve : Is this issue ready to close then?

**Comment by vv-monsalve** [comment]
Fonts in `lang-build` branch at commit `cc1f569` look good for v1 release. There are some kerning cases but I'll report about them in the issue related to it.
