### ISSUE TITLE
Roman and Italic VFs

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#29]
@josescaglione After reviewing the current status of italic fonts produced with an `slnt` axis, we've confirmed the requirement to split the Variable Fonts into Roman + Italics, as it is still [stated in our Guide](https://googlefonts.github.io/gf-guide/variable.html#ital--slnt).

This is necessary to ensure the Italic companions are visible and accessible from the Catalog and to receive the static counterparts in the .zip file for each font.

**Comment by vv-monsalve** [comment]
The fonts in the `lang-build` branch at commit `658f99f`.

@simoncozens this is still missing in builder2

**Comment by simoncozens** [comment]
Or is it?

```
simon@Simons-Air ~/Downloads/Playwrite-fonts-3 $ ls variable/PlaywriteGB*
'variable/PlaywriteGBJ-Italic[wght].ttf'
'variable/PlaywriteGBJ[wght].ttf'
'variable/PlaywriteGBS-Italic[wght].ttf'
'variable/PlaywriteGBS[wght].ttf'
```

**Comment by vv-monsalve** [comment]
They were not included in the local `make build` run.

After a private chat conversation with Simon, he said this is due to a dependency version. Simon is going to pin it later on when Builder2 has reached a more stable development process :)

**Comment by vv-monsalve** [comment]
The current `builder2` branch is creating separate fonts but I'm keeping this issue open until we ensure the STAT tables are working ok.

**Comment by vv-monsalve** [comment]
This has been solved. Closing it here.
