### ISSUE TITLE
Comprehensive specimen PDF

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#3]
@josescaglione Please generate a specimen PDF for the project, so we have a reference document using the stylistic sets and axes as expected on your end :) The old "system rationale" diagram with 7 lowercase sets was helpful to see

(Copying this issue here for tracking the inclusion of the specimen for the Playpen font, similar to [https://github.com/TypeTogether/Playpen-Sans/tree/main/documentation/PlaypenSans-Specimen](https://github.com/TypeTogether/Playpen-Sans/tree/main/documentation/PlaypenSans-Specimen))

**Comment by josescaglione** [comment]
@vv-monsalve I am not sure this is still needed. Please advice..

**Comment by vv-monsalve** [comment]
At today's meeting, we decided to close this issue since the Specimen info for each model will now be included in the About section of each one. 
We'll probably need an extended specimen document for the complete VF in the future. But we'll open a new issue at that moment.
