### ISSUE TITLE
Romanian and Moldovan localization

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#30]
@josescaglione, we are implementing a new check now for shaping languages that will ensure these requirements:

- [ ] We are not including `Tcedilla` nor `tcedilla` in out GF Latin Core Glyphset 
- [x] The `locl` feature for ROM and MOL by default (to replace `Scedilla` `scedilla` by S and s + commaaccent)

**Comment by casasin** [comment]
Fixed in new fonts.

**Comment by vv-monsalve** [comment]
The fonts in the `lang-build` branch at commit `658f99f` still include the T, t cedilla.

<img width="600" alt="Screen Shot 2024-02-06 at 15 57 02" src="https://github.com/TypeTogether/Playwrite/assets/48698976/846e8042-b898-4a39-bde7-9a98c78a0f35">

**Comment by vv-monsalve** [comment]
<details><summary>🔥 <b>FAIL:</b> Shapes languages in all GF glyphsets. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyphsets/shape_languages">com.google.fonts/check/glyphsets/shape_languages</a>)</summary><div>

>
>This check uses a heuristic to determine which GF glyphsets a font supports. Then it checks the font for correct shaping behaviour for all languages in those glyphsets.
>
* 🔥 **FAIL** GF_Latin_Core glyphset:

| Language | FAIL messages |
| :--- | :--- |
| nl_Latn (Dutch) | Shaper didn't attach acutecomb to j.jmc.fin |
| ro_Latn (Romanian) | in Romanian, S-cedilla should become S-comma-accent; both buffers returned S.dec=0+941|uni0327.case=0@-583,0+0 |

 [code: failed-language-shaping]
</div></details>

This Fail is reported for the following families:

- AR.md
- AU-NSW.md
- AU-QLD.md
- AU-SA.md
- AU-TAS.md
- AU-VIC.md
- BE-VLG.md
- BE-WAL.md
- BR.md
- CA.md
- CL.md
- CU.md
- CZ.md
- DE-Gru.md
- DE-LA.md
- DE-SAS.md
- DE-VA.md
- DK-Loopet.md
- DK-Uloopet.md
- EE.md
- ES-Ornate.md
- ES.md
- FR-Modern.md
- HR-Lijeva.md
- HR.md
- HU.md
- ID.md
- IE.md
- IS.md
- IT-Modern.md
- IT-Trad.md
- MX.md
- NO.md
- NZ.md
- PE.md
- PL.md
- PT.md
- RO.md
- SK.md
- TZ.md
- US-Modern.md
- US-Trad.md
- VN.md
- ZA.md

**Comment by josescaglione** [comment]
@vv-monsalve just to let you know that we tested this on our latest fonts and it seems solved. Could you please test and confirm?

**Comment by vv-monsalve** [comment]
This was fixed for fonts in `lang-build` branch at commit `cc1f569`
