### ISSUE TITLE
GB-SemiJoined-Italic `hhea.caretSlopeRun` value

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#31]
<details><summary>🔥 <b>FAIL:</b> Check hhea.caretSlopeRise and hhea.caretSlopeRun (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/hhea.html#com.google.fonts/check/caret_slope">com.google.fonts/check/caret_slope</a>)</summary><div>

>
>Checks whether hhea.caretSlopeRise and hhea.caretSlopeRun match with post.italicAngle.
>
>For Upright fonts, you can set hhea.caretSlopeRise to 1 and hhea.caretSlopeRun to 0.
>
>For Italic fonts, you can set hhea.caretSlopeRise to head.unitsPerEm and calculate hhea.caretSlopeRun like this: round(math.tan( math.radians(-1 * font["post"].italicAngle)) * font["head"].unitsPerEm)
>
>This check allows for a 0.1° rounding difference between the Italic angle as calculated by the caret slope and post.italicAngle
>
* 🔥 **FAIL** hhea.caretSlopeRise and hhea.caretSlopeRun do not match with post.italicAngle.
Got: caretSlopeRise 1000 and caretSlopeRun 231
Expected: caretSlopeRise 1000 and caretSlopeRun 123 [code: caretslope-mismatch]
</div></details>

**Comment by casasin** [comment]
This is fixed in latest fonts. Close the issue after checking this is ok again.

**Comment by vv-monsalve** [comment]
Confirming this is no longer reported for the font at commit `f68964`
