### ISSUE TITLE
Please change the OFL url

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#34]
This change is required after SIL changed the Open Font License website.
You can see more context on this on [#7062](https://github.com/google/fonts/issues/7062).

**Comment by casasin** [comment]
This has been changed in sources `lang-build` branch and in OFL.txt `main`

**Comment by casasin** [comment]
Buut very latest `fontbakery` (v0.10.8) is reporting this: 

> 🔥 FAIL
License file OFL.txt exists but NameID 13 (LICENSE DESCRIPTION) value on platform 3 (WINDOWS) is not specified for that. Value was: "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://openfontlicense.org/" Must be changed to "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL" [code: wrong]

What I assume is something that needs to be updated in `fontbakery` itself, is this right @vv-monsalve ?

**Comment by chrissimpkins** [comment]
The fontbakery update will land in https://github.com/fonttools/fontbakery/pull/4409

**Comment by vv-monsalve** [comment]
The fonts in `lang-build` branch at commit `658f99f` still need to use the new URL `https://openfontlicense.org/`

<img width="757" alt="Screen Shot 2024-02-06 at 15 44 38" src="https://github.com/TypeTogether/Playwrite/assets/48698976/1f7b4c62-d778-4e52-ab31-71d2f5651cf5">

**Comment by casasin** [comment]
@vv-monsalve :  Probably it was only fixed in the sandbox fonts. Latest fonts (I updated them all) should have this fixed.

**Comment by vv-monsalve** [comment]
This was fixed for fonts in `lang-build` branch at commit `cc1f569`
