### ISSUE TITLE
The variable font origin should be `Regular`

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#36]
@simoncozens, the following Fail is reported for `Playwrite ES Deco`, but it is caused by the fact that the current font origin is `Thin` and should be `Regular`, for all the fonts.

<details>
    <summary>🔥 <b>FAIL</b> Combined length of family and style must not exceed 32 characters. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/googlefonts.name.html#"></a></summary>
    <div>

> 
> This check ensures that the length of name table entries is not
> too long, as this causes problems in some environments.
> 

> Original proposal: https://github.com/fonttools/fontbakery/issues/1488
> See also: https://github.com/fonttools/fontbakery/issues/2179

* 🔥 **FAIL** <p>Variable font instance name 'Playwrite ES Deco Thin ExtraLight' formed by space-separated concatenation of font family name (nameID 1) and instance subfamily nameID 285 exceeds 32 characters.</p>
<p>This has been found to cause shaping issues for some accented letters in Microsoft Word on Windows 10 and 11.</p>
 [code: instance-too-long]

</div>
</details>

**Comment by simoncozens** [comment]
Looks like @casasin removed the "Variable Font Origin" custom parameter in the last commit. 

@casasin I am going to avoid touching the sources now - there should be a custom parameter "Variable Font Origin" with value "Reg 00 Short Slow" in the main font info; please put it back!

**Comment by casasin** [comment]
It seems with the last upd

> Looks like @casasin removed the "Variable Font Origin" custom parameter in the last commit.

Not really. I'll talk with the designers to assure nothing else gets touched than whatever is updated.

**Comment by casasin** [comment]
This has been fixed.
