### ISSUE TITLE
Naming proposal

### ISSUE THREAD

**Issue by josescaglione** [TypeTogether/Playwrite#4]
We updated our fon reference spreadsheet [HERE](https://docs.google.com/spreadsheets/d/1nA9Z8vDahOpjzaftFVOLyOxrsDPPCaorA4AnAJnhtpE/edit?usp=sharing)

We are proposing the following family naming scheme for revision and approval

Family names must identify and represent each region or handwriting style, be as consistent as possible, and be within reasonable length limits. One of the issues is that the differences from model to model in a given country can be historical, formal, or geographic. We decided to use local nomenclature for geographic or model naming when possible, and english suffixes for other cases.

So:
Playpen + [3-letter country code] + suffix where necessary

**Some examples**
Playpen BRA
Playpen AUS NSW 
Playpen HRV Lefthand
Playpen FRA Traditional

Regarding style name the obvious ones are
**Thin Extralight** (or is it **ExtraLight**) **Light Regular**
**Italic** where appropriate
And possible **Guidelines** or **Dotted** for special versions

Please share your comments.

ps. The number of families in the system is now 46

**Comment by vv-monsalve** [comment]
The only remaining open question related to naming would be related to the Guidelines version.
However, I'm closing this here and will reopen or open a new issue to discuss when the time comes.

**Comment by vv-monsalve** [comment]
There are two questions still open. Taken from the Handriting Families Name spreadsheet

### Nigeria
Original comments
> This model serves to Private schols only. We cannot produce a public school one because it is a regular sans serif font and therefore outside our scope. I wonder if we should somehow specify it is for private schools. 
> this is a Modern cursive, The other model is a typeface, closer to a print model. Maybe we should do "Modern"?

- [ ] Should we use "Modern"

### Playwrite ES Ornate
- [ ] Changing `Playwrite ES Ornate` to `Playwrte ES Deco` to localize the name 

### Playwrite England Semijoined
> Let's keep the syntax in sync with the abbreviation (and e.g. the CamelCased usWeightClass in OT) SemiJoined

- [ ] Should wechange to SemiJoined?

cc @davelab6

**Comment by vv-monsalve** [comment]
@davelab6, @chrissimpkins, we still need to resolve the above three cases.

**Comment by vv-monsalve** [comment]
After private conversations with Dave, Chris, and José, the above boxes were ticked.

Some other decisions made were:

- All the Model Variant names will be localized. For example, in the France and Italy models, the "Traditional" fonts will be called `Traditionnelle` and `Tradizionale`.
- Everywhere the full names appear, the Variant name will have the unabbreviated version. E.g. Playwrite DE VA will be displayed as `Playwrite Germany Vereinfachte Ausgangsschrift`
