### ISSUE TITLE
⚠️ WARN Ensure Stylistic Sets have description.

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#41]
@simoncozens, the Stylistic Sets have lost their names. 

The names seem included in the `name` table but are not recognized in the fonts. Actually, something weird is happening in the table in general: the other axes appear listed (slant, speed, Y extension), and the instances are listed more than once (pics below).

<details>
    <summary>⚠️ <b>WARN</b> Ensure Stylistic Sets have description. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/googlefonts.gsub.html#"></a></summary>
    <div>
> 
> Stylistic sets should provide description text. Programs such as InDesign,
> TextEdit and Inkscape use that info to display to the users so that they know
> what a given stylistic set offers.
> 
> Original proposal: https://github.com/fonttools/fontbakery/issues/3155
* ⚠️ **WARN** <p>The stylistic set ss01 lacks a description string on the 'name' table.</p>
 [code: missing-description]
* ⚠️ **WARN** <p>The stylistic set ss02 lacks a description string on the 'name' table.</p>
 [code: missing-description]
* ⚠️ **WARN** <p>The stylistic set ss03 lacks a description string on the 'name' table.</p>
 [code: missing-description]
* ⚠️ **WARN** <p>The stylistic set ss04 lacks a description string on the 'name' table.</p>
 [code: missing-description]
* ⚠️ **WARN** <p>The stylistic set ss05 lacks a description string on the 'name' table.</p>
 [code: missing-description]
* ⚠️ **WARN** <p>The stylistic set ss06 lacks a description string on the 'name' table.</p>
 [code: missing-description]
* ⚠️ **WARN** <p>The stylistic set ss07 lacks a description string on the 'name' table.</p>
 [code: missing-description]
* ⚠️ **WARN** <p>The stylistic set ss19 lacks a description string on the 'name' table.</p>
 [code: missing-description]
* ⚠️ **WARN** <p>The stylistic set ss20 lacks a description string on the 'name' table.</p>
 [code: missing-description]
</div>
</details>

#### `name` table on latest build
<img width="500" alt="Screen Shot 2024-04-19 at 19 22 05" src="https://github.com/TypeTogether/Playwrite/assets/48698976/1e34dc52-538b-4ff1-871d-0bb98623fa2d">

#### `name` table from previous (TT) build
<img width="500" alt="Screen Shot 2024-04-19 at 19 30 00" src="https://github.com/TypeTogether/Playwrite/assets/48698976/ff7d8f13-b12a-4cfc-920f-255e2d9e1c92">

#### Comparison between builds
<img width="596" alt="Screen Shot 2024-04-19 at 19 09 35" src="https://github.com/TypeTogether/Playwrite/assets/48698976/16895a23-f12e-4099-a6e1-d21c8bb30f8d">

**Comment by simoncozens** [comment]
These appear to be dropped by the `remapLayout` step (when we move the locl/ccmp features into calt to stop the InDesign problem). So `gftools-remap-layout` is not maintaining these names; I'll fix the issue in gftools.
