### ISSUE TITLE
Different results between local build and the GHA

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#44]
@simoncozens, after testing the current fonts at commit `7dc6a43` in InDesign, and comparing the result with the latest control fonts from the `lang-build` branch, the shaping differences are back for some families.

~This is a regression from previous fonts on the `builder2` branch at commit `4cf78b1`, where these shaping issues were absent.~

Edit: The different results happen for the fonts produced locally after running the `make build` command, not those from the GHA. The CI-run fonts do not show these differences. What is needed to ensure 1:1 results between the local run and the CI build?

### Playwrite CO

![04-23-24-CO-GHA-7dc6a43-Vs-TTs](https://github.com/TypeTogether/Playwrite/assets/48698976/0b528a0e-49d2-4b50-9955-82ec6dd32f6a)

**Comment by simoncozens** [comment]
Please remember that you need to have the fixed version of harfbuzz installed on your computer to avoid the InDesign problem. If you are testing on InDesign 2023, I would use the CI builds.

**Comment by simoncozens** [comment]
Well, then we just make a requirement (in the documentation) that the user must use Harfbuzz >=8.4.0 on their system (Remember, this is a system package requirement, not a Python package) to build the fonts correctly, or they use the GHA versions.

**Comment by vv-monsalve** [comment]
We discussed making the CI fonts reliable for all users. Ensuring this requires:

- The CI build .yaml file to include a step that pushes the fonts into the repository
- To definitely not push locally built fonts into the repository
- To only push the latest changes made on source files

This doesn't mean the local build can't be done, but the centralized, reliable fonts should be the CI ones.
This would also impact the final [Build instructions](https://github.com/TypeTogether/Playwrite/issues/16), which will need to be defined in the Readme file.

cc @casasin
