### ISSUE TITLE
Remove the `Maximum` instance from the source file

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#65]
The `Maximum` instance included in the source file generates unnecessary and *repeated* static fonts. See this [example](https://github.com/TypeTogether/Playwrite/blob/main/fonts/ttf/PlaywriteAR-Maximum.ttf).

Please remove it to avoid confusion for users.

**Comment by casasin** [comment]
Done at commit `06485ee4b`.
At some point back in the days an instance with all maximum axis values was needed when building. I made a local test and built fonts without complains so I guess it will be ok now.
@vv-monsalve : Double check and close the issue if all is good now.

**Comment by vv-monsalve** [comment]
The "Maximum" Fonts are no longer there, so I'm closing this one here.
