### ISSUE TITLE
Issues to address on the next font version (WIP)

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#66]
Hi @josescaglione, I'll collect here all the reported issues on the fonts so they can be addressed in the next font release:

### Connection issues

- [x] [Playwrite HR](https://github.com/google/fonts/pull/7718#issuecomment-21492489120)
- [x] [Playwrite HR Lijeva](https://github.com/google/fonts/pull/7717#issuecomment-2150026446)
- [x] [Playwrite HU](https://github.com/google/fonts/pull/7719#issuecomment-2149203214)
- [x] [Playwrite CL](https://github.com/google/fonts/pull/7705#issuecomment-2151810618)
- [x] [Playwrite BE VLG](https://github.com/google/fonts/pull/7702#issuecomment-2151872272)
- [ ] [Playwrite AT](https://github.com/google/fonts/pull/7696#issuecomment-2151901160)
- [x] [Playwrite AR](https://github.com/google/fonts/pull/7695#issuecomment-2151916664)

### Anchors and comb marks

- [x] [Playwrite PE](https://github.com/google/fonts/pull/7731#issuecomment-2142158101)

### Spacing / Kerning

- [ ] [Playwrite PL](https://github.com/google/fonts/pull/7732#issuecomment-2139205028)
- [ ] [Playwrite DK Loopet](https://github.com/google/fonts/pull/7711#issuecomment-2151738525)
- [ ] [Playwrite BE WAL](https://github.com/google/fonts/pull/7703#issuecomment-2151850447)
- [ ] [Playwrite GB S](https://github.com/google/fonts/pull/7643#issuecomment-2104214126)

**Comment by josescaglione** [comment]
I am uploading comments for the issues pointed out in the list above. Note that the fixes were done in the **/fixes** branch

**Comment by josescaglione** [comment]
**Connection issue b.ful_o.mlp**

This is a minor connection issue that affects connections between b.ful v.ful w.ful and o.mlp
Tweaked shape of connector: cnct.ful_b_o

Models:
AR
BR
CL
ID
PT
RO
TZ


<img width="977" alt="Screen Shot 2024-06-10 at 12 44 42" src="https://github.com/TypeTogether/Playwrite/assets/1699496/32d61770-c035-4099-b424-70e8ceb67934">

**Comment by josescaglione** [comment]
**Connection issue e.mod_s.ful**

this issue affects the pair e.mod - s.mlp (*)
DIST feature required to align connection in the following fonts:

AU_QLD
HR
HR_LIJEVA
*DE_VA
HU
IN
NO

<img width="601" alt="Screen Shot 2024-06-07 at 10 36 16" src="https://github.com/TypeTogether/Playwrite/assets/1699496/2231609a-f9c0-4c50-8092-4949d24619e3">

**Comment by josescaglione** [comment]
**Connection issues with y.cnt**


This change fixes a minor issue when y.cnt appears in the middle of a word..
Fixes the following models:

AR BR CA CL CO CU CZ DE_LA ES ES_DECO FR_TRAD ID IN IT_TRAD MX NL PE PL PT RO SK TZ US_MOD US_TRAD

<img width="957" alt="Screen Shot 2024-06-10 at 14 49 40" src="https://github.com/TypeTogether/Playwrite/assets/1699496/78124fa2-94d3-4b0a-a100-38f45123821a">

**Comment by josescaglione** [comment]
**Outline fix in b.lop**

Made a small adjustment in the b.lop finial

<img width="419" alt="Screen Shot 2024-06-10 at 14 56 38" src="https://github.com/TypeTogether/Playwrite/assets/1699496/a0ffd85d-55e3-4d17-a8fb-4e4414129c16">

**Comment by josescaglione** [comment]
ohorn and Ohorn collision with tilde.

This issue happens when generating the Vietnamese glyph ohorntilde and Ohorntilde on the fly, for slanted models. eg. IS

The issue cannot be easily solved at the moment without affecting other models. However, the issue does not affect the VN (Vietnam) model. This may be probably fixed in the futureby removing the ohorn character from CCMP code.

<img width="434" alt="Screenshot 2024-06-11 at 15 24 42" src="https://github.com/TypeTogether/Playwrite/assets/1699496/70b75b06-4527-45c9-a7e0-427db057f493">

**Comment by josescaglione** [comment]
**Connection issue Ce**

This fix amends two types of problems with this connection.

The first one is between C and e.ful
This was solved by positive kerning in Models:
DE SAS - DL Loopet - DL Uloopet - ES - ZA

Second issue is connecting C.cur with e.mod
Problem required fix of Trackback code in CALT fixing anchor placement in Master 6
This affects: HR - HR Lijeva - HU - IE - IN - NO - 

<img width="449" alt="Screenshot 2024-06-12 at 07 27 40" src="https://github.com/TypeTogether/Playwrite/assets/1699496/7c679814-473e-4fdd-847d-1686a07bc78e">

**Comment by josescaglione** [comment]
**Connection issue ar**

Fixed a minor connection issue reported in the thin weight of BE_VLG
<img width="479" alt="Screenshot 2024-06-12 at 07 49 44" src="https://github.com/TypeTogether/Playwrite/assets/1699496/394dc1e0-458d-4991-8b97-50fd57de5644">

**Comment by tommai4881** [comment]
Add playwrite Sutterlin (Playwrite DE Traditional)

**Comment by vv-monsalve** [comment]
@tommai4881, as commented in #69 this is not planned.

**Comment by vv-monsalve** [comment]
> Connection issue e.mod_s.ful

Confirmed it's working ok now.

**Comment by vv-monsalve** [comment]
> Anchor position. A.cur A.cur.ini

Confirmed it is working on fonts in `Fixes` branch at commit `3608fc Automated rebuild`

**Comment by vv-monsalve** [comment]
@josescaglione, a couple of the issues reported in [Playwrite BE VLG](https://github.com/google/fonts/pull/7702#issuecomment-2151872272) are still present. Would you like to double-check them?
<img width="743" alt="Screenshot 2024-10-30 at 20 49 54" src="https://github.com/user-attachments/assets/42f1681a-3893-4d07-8ea6-d9d535df35c5">

**Comment by vv-monsalve** [comment]
> Connection issue b.ful_o.mlp

Confirmed it is working on fonts in `Fixes` branch at commit `3608fc Automated rebuild`

**Comment by vv-monsalve** [comment]
> Connection issue ar
> Fixed a minor connection issue reported in the thin weight of BE_VLG


Confirmed it is working on fonts in `Fixes` branch at commit `3608fc Automated rebuild`

**Comment by josescaglione** [comment]
> @josescaglione, a couple of the issues reported in [Playwrite BE VLG](https://github.com/google/fonts/pull/7702#issuecomment-2151872272) are still present. Would you like to double-check them?
> <img alt="Screenshot 2024-10-30 at 20 49 54" width="743" src="https://private-user-images.githubusercontent.com/48698976/381794624-42f1681a-3893-4d07-8ea6-d9d535df35c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzM2MDIsIm5iZiI6MTczMDM3MzMwMiwicGF0aCI6Ii80ODY5ODk3Ni8zODE3OTQ2MjQtNDJmMTY4MWEtMzg5My00ZDA3LThlYTYtZDlkNTM1ZGYzNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDExMTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZTc2MjczYTNiM2I3ODBiNGIyMjM1ZDFiZjQ4NTZiYTFhMDQyZjdhMGYxY2M2NGNmYTgyMmFiMGRhMjA5MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.of0cgV3VGsGQZTE0Wg74C6vuqsPu1yxVoE7uP57x-94">

Both of these look as intended.

**Comment by vv-monsalve** [comment]
> **Connection issue Ce**
> This fix amends two types of problems with this connection.

Confirmed it is working on fonts in `Fixes` branch at `commit 3608fc Automated rebuild`

Before status above, new, below.
<img width="271" alt="Screenshot 2024-10-31 at 14 45 23" src="https://github.com/user-attachments/assets/def44019-623e-4c46-a7bf-c95146e7d3c5">

**Comment by vv-monsalve** [comment]
> Second issue is connecting C.cur with e.mod
> This affects: HR - HR Lijeva - HU - IE - IN - NO -

Confirmed it is working on fonts in `Fixes` branch at commit `3608fc Automated rebuild`

Before status above, new, below.

<img width="496" alt="Screenshot 2024-10-31 at 14 50 21" src="https://github.com/user-attachments/assets/9cbb224d-d33b-4a6d-bbbf-9ea1ec004862">

**Comment by vv-monsalve** [comment]
> **ohorn and Ohorn collision with tilde.**
> (…)
> This may be probably fixed in the futureby removing the ohorn character from CCMP code.

@josescaglione are you planning on doing this for the next font version?

**Comment by josescaglione** [comment]
@josescaglione Since these fonts are language-specific I do not consider this fiz a priority. As I mentioned, there is NO collision in the Viet model,

**Comment by vv-monsalve** [comment]
> Since these fonts are language-specific I do not consider this fiz a priority

Ok. We'll continue with them as they are now.

**Comment by vv-monsalve** [comment]
Some of the reported kerning cases cases (`Ty` `To` `Tw`) are still present in the latest fonts. 
Please see this [comment in the Kerning issue](https://github.com/TypeTogether/Playwrite/issues/14#issuecomment-2450800290). 

I'm closing this issue here. Let's finish the kerning revision on that issue.
