### ISSUE TITLE
Playwrite Guides

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#83]
Hi @simoncozens 
Related to #82

The font version for the Playwrite Guides should be bumped to `1.003` to make it match the next font version for the default ones. I've opened a PR with the font version bumped to 1.003 so we can continue with the PRs to GF.

cc @casasin @josescaglione,

**Comment by casasin** [comment]
@vv-monsalve I guess this can be closed, right?

**Comment by vv-monsalve** [comment]
SUre!
